name: "Terraform Lint"
on:
  pull_request:
    paths:
      - "**.tf"

permissions:
  contents: read
  pull-requests: write

jobs:
  terraform-lint:
    name: "Terraform Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: "Terraform Setup"
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6

      - name: Terraform lint
        id: tflint
        run: tflint
        continue-on-error: true

      - name: "Terraform Init"
        id: init
        run: terraform init -backend=false -no-color
        continue-on-error: true

      - name: "Terraform Format"
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: "Terraform Validate"
        id: validate
        shell: bash
        run: terraform validate -no-color
        continue-on-error: true

      - name: Run terraform-docs
        id: docs
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c # v1
        with:
          working-dir: .
          output-file: ./README.md
          output-method: inject
          output-format: markdown

      - name: Hide previous comments from github-actions
        if: |
          always() &&
          github.event_name == 'pull_request'
        uses: int128/hide-comment-action@afc35066cef9f89f60a2022988cadb58445a208e # v1

      - name: "Comment PR"
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9
        if: steps.init.outcome == 'failure' || steps.fmt.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.tflint.outcome == 'failure' || steps.docs.outcome == 'failure'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Fmt ⚙️\`${{ steps.fmt.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Lint ⚙️\`${{ steps.tflint.outcome }}\`
            #### Terraform Docs ⚙️\`${{ steps.docs.outcome }}\`
            `
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: "Block PR if error"
        if: steps.init.outcome == 'failure' || steps.fmt.outcome == 'failure' || steps.validate.outcome == 'failure' || steps.tflint.outcome == 'failure' || steps.docs.outcome == 'failure'
        run: exit 1
